# Header
navbar_brand:
menu:
  Index: /
  Archive: archive/

# RSS
rss:

# Content
favicon: favicon.ico
excerpt_link: Read More
fancybox: true

# Sidebar
widgets:
- about
- category
- tag
- tagcloud
- archive
- recent_posts
about_widget_content: >
  <p>Etiam porta <em>sem malesuada magna</em> mollis euismod.
  Cras mattis consectetur purus sit amet fermentum. Aenean
  lacinia bibendum nulla sed consectetur.</p>

# Widgets
archive_type: 'monthly'
show_count: true

# Meta Maker
title_divider:
twitter_creator:
twitter_site:
google_plus:
fb_personal_id: ""
fb_page_id:
fb_admins:
fb_app_id:
og_image_url: ""

# Analytics
google_analytics: